SASS configuration
atlp-rwanda/wolves-bn-frontend pull request #4
Opened 2020-11-11 09:25 UTC by Thom-IT

2020-11-11 10:55 UTC, Cherubln requested changes
Nice @Thom-IT 
I saw there are some development stuffs in the webpack.config.js like isdevelopment, devServer, etc . It will be much better if anything related to development  is kept in the webapack.dev.js because webpack.config.js is only for production.

2020-11-12 10:41 UTC, minega25 requested changes

2020-11-12 10:41 UTC, minega25 commented on src/styles/scss/main.scss
> +    // display: flex;
Lets remove all commented code.

2020-11-12 10:41 UTC, minega25 commented on webpack.config.js
> +            }
I thought we got rid of the isDevelopment variable

2020-11-12 10:41 UTC, minega25 commented on webpack.dev.js
> +const isDevelopment = process.env.NODE_ENV !== 'production';
There is no need for this variable anymore

2020-11-12 13:44 UTC, minega25 approved these changes

2020-11-12 14:20 UTC, Cherubln approved these changes
Looks good to me

2020-11-16 10:37 UTC, merged